version: '3'

services:
  node-docker-express:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    container_name: node-docker-express
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev
